name: Benchmark Analysis

on:
  workflow_run:
    workflows: ["Benchmark Tests"]
    types:
      - completed

jobs:
  analyze-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JMeter results from artifacts
        uses: actions/download-artifact@v3
        with:
          name: jmeter-results
          path: .github/performance_tests/results

      - name: Run Benchmark Analysis
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter  # Use 'customBiggerIsBetter' if measuring throughput
          output-file-path: .github/performance_tests/results/results_*.jtl
          external-data-json-path: .github/benchmarks/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          name: Benchmark Results
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
          skip-fetch-gh-pages: false
          comment-always: false
          summary-always: false
          save-data-file: true
          comment-on-alert: false
          alert-threshold: 200%
          fail-on-alert: false

      - name: Upload Updated Benchmark Data
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-data
          path: .github/benchmarks/
