name: Run Performance Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Clone TeaStore repository
      run: |
        git clone https://github.com/DescartesResearch/TeaStore.git /d/Me/Lancaster/Third\ Year\ Project/performance-benchmarking-ci/TeaStore

    - name: Navigate to the TeaStore directory
      run: cd /d/Me/Lancaster/Third\ Year\ Project/performance-benchmarking-ci/TeaStore

    - name: Build Docker containers
      run: |
        echo "Building docker containers..." 
        chmod +x ./.github/build_docker.sh
        ./.github/build_docker.sh

      # Installing wrk to run the load tests
    - name: Install wrk
      run : |
        sudo apt-get update
        sudo apt-get install -y wrk  

    - name: Run Benchmark Script
      run: |
        bash ./.github/run-benchmark.sh
