name: Run Performance Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Clone TeaStore repository
      run: |
        git clone https://github.com/DescartesResearch/TeaStore.git ./TeaStore

    - name: List Contents After Clone
      run: |
        echo "Listing contents after cloning TeaStore:"
        ls -la ./TeaStore  # List the files and directories after clone

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      run: sudo apt-get install maven -y

    - name: Build TeaStore project
      run: cd ./TeaStore && mvn clean package -DskipTests


    - name: Build Docker containers
      run: |
        echo "Building docker containers..." 
        cd ./TeaStore
        export DEPLOY=0
        ./tools/build_docker.sh

        # chmod +x ./.github/build_docker.sh
        # ./.github/build_docker.sh

    - name: Run Benchmark Script
      run: |
        bash ./.github/run-benchmark.sh
