name: Run Performance Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Clone TeaStore repository
      run: |
        git clone https://github.com/DescartesResearch/TeaStore.git ./TeaStore

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      run: sudo apt-get install maven -y

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    

    - name: Build TeaStore project
      run: cd ./TeaStore && mvn clean package -DskipTests


    - name: Build Docker containers
      run: |
        echo "Building docker containers..." 
        cd ./TeaStore/tools
        export DEPLOY=0
        ./build_docker.sh
    
    - name: List Docker Images
      run: |
        echo "Listing available Docker images..."
        docker images

    - name: Start Docker containers
      run: |
        cd ./TeaStore/examples/docker/
        docker-compose -f docker-compose_default.yaml up -d
        
    - name: Install Latest JMeter
      run: |
        chmod +x ./.github/scripts/install-jmeter.sh
        sudo ./.github/scripts/install-jmeter.sh

    - name: Verify JMeter Installation
      run: |
        jmeter -v
  
    
    - name: Run Benchmark Script
      run: |
        bash ./.github/run-benchmark.sh

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
          name: jmeter-results
          path: ./performance_tests/results
        
        
    - name: Stop Docker containers
      if: always()
      run: |
        cd ./TeaStore/examples/docker/
        docker-compose -f docker-compose_default.yaml down