name: Run Performance Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Clone TeaStore repository
      run: |
        git clone https://github.com/DescartesResearch/TeaStore.git ./TeaStore

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      run: sudo apt-get install maven -y

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build TeaStore project
      run: cd ./TeaStore && mvn clean package -DskipTests

    - name: Build Docker containers
      run: |
        echo "Building docker containers..." 
        cd ./TeaStore/tools
        export DEPLOY=0
        ./build_docker.sh
    
    - name: List Docker Images
      run: |
        echo "Listing available Docker images..."
        docker images

    - name: Start Docker containers
      run: |
        cd ./TeaStore/examples/docker/
        docker-compose -f docker-compose_default.yaml up -d

    - name: Run Benchmark Script
      run: |
        bash ./.github/scripts/run-benchmark.sh


    - name: Inspect JTL Output
      run: cat .github/performance_tests/results/*.jtl
      

    - name: Convert JTL to JSON
      run: |
        python3 .github/scripts/jtl_to_json.py .github/performance_tests/results/*.jtl .github/performance_tests/results/benchmark-results.json

    - name: Upload Benchmark Results (JSON)
      uses: actions/upload-artifact@v4
      with:
          name: benchmark-results
          path: .github/performance_tests/results/benchmark-results.json
          if-no-files-found: warn

    - name: Run Benchmark Analysis
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: customSmallerIsBetter
        output-file-path: .github/performance_tests/results/benchmark-results.json
        external-data-json-path: .github/benchmarks/benchmark-data.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        name: Benchmark Results
        gh-pages-branch: gh-pages
        benchmark-data-dir-path: dev/bench
        skip-fetch-gh-pages: false
        comment-always: false
        summary-always: false
        save-data-file: true
        comment-on-alert: false
        alert-threshold: 200%
        fail-on-alert: false
             
    # - name: List JMeter Results Directory
    #   run: ls -l .github/performance_tests/results/
             
    - name: Stop Docker containers
      if: always()
      run: |
        cd ./TeaStore/examples/docker/
        docker-compose -f docker-compose_default.yaml down
