name: Run Performance Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker containers
      run: |
        echo "Building docker containers..." 
        chmod +x ./.github/build_docker.sh
        ./.github/build_docker.sh

    - name: Run Benchmark Script
      run: |
        bash ./.github/run-benchmark.sh
